### ISSUE TITLE
FE_Footer css 수정요청

### ISSUE THREAD

**Issue by qazx960** [codestates-seb/seb45_pre_021#20]
## 📁 이슈 내용

- CSS 추가 작업 요청

## 📝 작업 내용

- css 속성 사용해 화면 하단에 고정 시키는 추가 작업 요청드립니다! 

## 📍ETC

기타사항

**Comment by donghun-k** [comment]
푸터는 헤더와 달리 항상 화면에 보이게 할 건 아니고 그냥 페이지 맨 하단에 위치하면 되기 때문에,
레이아웃 컴포넌트를 작성하거나 페이지 컴포넌트 작성할 때 푸터 컴포넌트를 맨 밑에 배치하기만 하면 되어,
추가로 작업이 필요한 부분은 없는 것으로 생각됩니다.
혹시 헤더, 사이드바와 통합해서 페이지 작성 시 레이아웃 배치에 문제가 있으셨나요?

**Comment by qazx960** [comment]
@donghun-k  확인 감사합니다. 저희 메인페이지 같은 경우 scrolling 없이 화면에 전부 다 렌더링 되게끔 구현하는데 만약 footer가 fixed 안되어 있으면 footer가 화면에서 밀리는 것을 확인할 수 있습니다. 보통 메인페이지에는 height: 100vh 속성을 주는데, 만약 height 100vh 아닌 저희가 직접 정하면 사용자마다 화면 크기가 다르기 때문에 레이아웃이 조금 무너질 수도 있습니다. 

그래서 제가 생각했던 솔루션은 Footer에 fixed 속성을 주면 괜찮지 않을까라는 생각이 들었습니다.  혹시 동훈님께서 다른 아이디어가 있으실까요?

**Comment by donghun-k** [comment]
Case Closed!
